### ISSUE TITLE
Installation of boxmot on Python >= 3.10 seems to fail due to filterpy

### ISSUE THREAD

**Issue by poke1024** [mikel-brostrom/boxmot#1667]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

`filterpy` seems unsupported on Python >= 3.10, I get the following error when trying to install `boxmot` or `filterpy` individually:

```
Collecting filterpy
  Using cached filterpy-1.4.5.zip (177 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      /Users/ch/miniconda3/envs/py310/lib/python3.10/site-packages/setuptools/dist.py:452: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.
      
              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      running egg_info
      creating /private/var/folders/g6/bvk9tq0s4qd7vk0lc6gxf4l80000gp/T/pip-pip-egg-info-h_d0461t/filterpy.egg-info
      writing /private/var/folders/g6/bvk9tq0s4qd7vk0lc6gxf4l80000gp/T/pip-pip-egg-info-h_d0461t/filterpy.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/g6/bvk9tq0s4qd7vk0lc6gxf4l80000gp/T/pip-pip-egg-info-h_d0461t/filterpy.egg-info/dependency_links.txt
      writing requirements to /private/var/folders/g6/bvk9tq0s4qd7vk0lc6gxf4l80000gp/T/pip-pip-egg-info-h_d0461t/filterpy.egg-info/requires.txt
      writing top-level names to /private/var/folders/g6/bvk9tq0s4qd7vk0lc6gxf4l80000gp/T/pip-pip-egg-info-h_d0461t/filterpy.egg-info/top_level.txt
      writing manifest file '/private/var/folders/g6/bvk9tq0s4qd7vk0lc6gxf4l80000gp/T/pip-pip-egg-info-h_d0461t/filterpy.egg-info/SOURCES.txt'
      reading manifest file '/private/var/folders/g6/bvk9tq0s4qd7vk0lc6gxf4l80000gp/T/pip-pip-egg-info-h_d0461t/filterpy.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.py' under directory 'filterpy/monte_carlo/tests'
      adding license file 'LICENSE'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/g6/bvk9tq0s4qd7vk0lc6gxf4l80000gp/T/pip-install-e4js_xgm/filterpy_69aca147eb474ea4af3e387a4691d061/setup.py", line 12, in <module>
          setup(
        File "/Users/ch/miniconda3/envs/py310/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/Users/ch/miniconda3/envs/py310/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/Users/ch/miniconda3/envs/py310/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/Users/ch/miniconda3/envs/py310/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/Users/ch/miniconda3/envs/py310/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/Users/ch/miniconda3/envs/py310/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/Users/ch/miniconda3/envs/py310/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 311, in run
          self.find_sources()
        File "/Users/ch/miniconda3/envs/py310/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 319, in find_sources
          mm.run()
        File "/Users/ch/miniconda3/envs/py310/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 545, in run
          self.prune_file_list()
        File "/Users/ch/miniconda3/envs/py310/lib/python3.10/site-packages/setuptools/command/sdist.py", line 161, in prune_file_list
          super().prune_file_list()
        File "/Users/ch/miniconda3/envs/py310/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 380, in prune_file_list
          base_dir = self.distribution.get_fullname()
        File "/Users/ch/miniconda3/envs/py310/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 267, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
        File "/Users/ch/miniconda3/envs/py310/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 285, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Since `filterpy` seems unmaintained, I guess this might be a problem.

For the moment, I worked around the issue by installing `filterpy` via `conda-forge::filterpy`.

**Comment by mikel-brostrom** [comment]
Sorry, I have never tried to install this pkg using `conda`. The installation using the method in the repo works for `python >= 3.9`

**Comment by poke1024** [comment]
The method described in the README works for me too. Seems that installation via `poetry` is not affected by the `filterpy` issue. This is the best solution then for me too.

Also, installation via `conda install` works.

But `pip install boxmot` inside any env with python >= 3.10 fails. For example, this fails:

```
conda create -n testboxmot python=3.10
conda activate testboxmot
pip install boxmot
```

Which basically makes it impossible to reference `boxmot` as dependency in another pip-packaged project.

**Comment by mikel-brostrom** [comment]
Just installed BoxMOT on a clean python 3.11 environment:

```bash
➜  yolo_boxmot git:(main) ✗ python3 -m venv myenv                            
source myenv/bin/activate  # On Windows use: myenv\Scripts\activate
pip install --upgrade pip setuptools wheel
Requirement already satisfied: pip in ./myenv/lib/python3.11/site-packages (23.2.1)
Collecting pip
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/d4/55/90db48d85f7689ec6f81c0db0622d704306c5284850383c090e6c7195a5c/pip-24.2-py3-none-any.whl.metadata
  Using cached pip-24.2-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: setuptools in ./myenv/lib/python3.11/site-packages (65.5.0)
Collecting setuptools
  Obtaining dependency information for setuptools from https://files.pythonhosted.org/packages/ff/ae/f19306b5a221f6a436d8f2238d5b80925004093fa3edea59835b514d9057/setuptools-75.1.0-py3-none-any.whl.metadata
  Downloading setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
Collecting wheel
  Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/1b/d1/9babe2ccaecff775992753d8686970b1e2755d21c8a63be73aba7a4e7d77/wheel-0.44.0-py3-none-any.whl.metadata
  Using cached wheel-0.44.0-py3-none-any.whl.metadata (2.3 kB)
Using cached pip-24.2-py3-none-any.whl (1.8 MB)
Downloading setuptools-75.1.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 6.5 MB/s eta 0:00:00
Using cached wheel-0.44.0-py3-none-any.whl (67 kB)
Installing collected packages: wheel, setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 65.5.0
    Uninstalling setuptools-65.5.0:
      Successfully uninstalled setuptools-65.5.0
  Attempting uninstall: pip
    Found existing installation: pip 23.2.1
    Uninstalling pip-23.2.1:
      Successfully uninstalled pip-23.2.1
Successfully installed pip-24.2 setuptools-75.1.0 wheel-0.44.0
(myenv) ➜  yolo_boxmot git:(main) ✗ pip install boxmot
Collecting boxmot
  Downloading boxmot-10.0.84-py3-none-any.whl.metadata (18 kB)
Collecting filterpy<2.0.0,>=1.4.5 (from boxmot)
  Using cached filterpy-1.4.5-py3-none-any.whl
Collecting ftfy<7.0.0,>=6.1.3 (from boxmot)
  Using cached ftfy-6.2.3-py3-none-any.whl.metadata (7.8 kB)
Collecting gdown<6.0.0,>=5.1.0 (from boxmot)
  Using cached gdown-5.2.0-py3-none-any.whl.metadata (5.8 kB)
Collecting gitpython<4.0.0,>=3.1.42 (from boxmot)
  Using cached GitPython-3.1.43-py3-none-any.whl.metadata (13 kB)
Collecting lapx<0.6.0,>=0.5.5 (from boxmot)
  Downloading lapx-0.5.10.post1-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.1 kB)
Collecting loguru<0.8.0,>=0.7.2 (from boxmot)
  Using cached loguru-0.7.2-py3-none-any.whl.metadata (23 kB)
Collecting numpy==1.26.4 (from boxmot)
  Using cached numpy-1.26.4-cp311-cp311-macosx_11_0_arm64.whl.metadata (114 kB)
Collecting opencv-python<5.0.0,>=4.7.0 (from boxmot)
  Using cached opencv_python-4.10.0.84-cp37-abi3-macosx_11_0_arm64.whl.metadata (20 kB)
Collecting pandas<3.0.0,>=2.0.0 (from boxmot)
  Downloading pandas-2.2.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (89 kB)
Collecting pyyaml<7.0.0,>=6.0.1 (from boxmot)
  Using cached PyYAML-6.0.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.1 kB)
Collecting regex<2025.0.0,>=2024.0.0 (from boxmot)
  Downloading regex-2024.9.11-cp311-cp311-macosx_11_0_arm64.whl.metadata (40 kB)
Collecting scikit-learn<2.0.0,>=1.3.0 (from boxmot)
  Downloading scikit_learn-1.5.2-cp311-cp311-macosx_12_0_arm64.whl.metadata (13 kB)
Collecting torch<3.0.0,>=2.2.1 (from boxmot)
  Using cached torch-2.4.1-cp311-none-macosx_11_0_arm64.whl.metadata (26 kB)
Collecting torchvision<0.18.0,>=0.17.1 (from boxmot)
  Using cached torchvision-0.17.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.6 kB)
Collecting yacs<0.2.0,>=0.1.8 (from boxmot)
  Using cached yacs-0.1.8-py3-none-any.whl.metadata (639 bytes)
Collecting scipy (from filterpy<2.0.0,>=1.4.5->boxmot)
  Using cached scipy-1.14.1-cp311-cp311-macosx_14_0_arm64.whl.metadata (60 kB)
Collecting matplotlib (from filterpy<2.0.0,>=1.4.5->boxmot)
  Using cached matplotlib-3.9.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (11 kB)
Collecting wcwidth<0.3.0,>=0.2.12 (from ftfy<7.0.0,>=6.1.3->boxmot)
  Using cached wcwidth-0.2.13-py2.py3-none-any.whl.metadata (14 kB)
Collecting beautifulsoup4 (from gdown<6.0.0,>=5.1.0->boxmot)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting filelock (from gdown<6.0.0,>=5.1.0->boxmot)
  Downloading filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
Collecting requests[socks] (from gdown<6.0.0,>=5.1.0->boxmot)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting tqdm (from gdown<6.0.0,>=5.1.0->boxmot)
  Using cached tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)
Collecting gitdb<5,>=4.0.1 (from gitpython<4.0.0,>=3.1.42->boxmot)
  Using cached gitdb-4.0.11-py3-none-any.whl.metadata (1.2 kB)
Collecting python-dateutil>=2.8.2 (from pandas<3.0.0,>=2.0.0->boxmot)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas<3.0.0,>=2.0.0->boxmot)
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas<3.0.0,>=2.0.0->boxmot)
  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting joblib>=1.2.0 (from scikit-learn<2.0.0,>=1.3.0->boxmot)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn<2.0.0,>=1.3.0->boxmot)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Collecting typing-extensions>=4.8.0 (from torch<3.0.0,>=2.2.1->boxmot)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting sympy (from torch<3.0.0,>=2.2.1->boxmot)
  Downloading sympy-1.13.3-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch<3.0.0,>=2.2.1->boxmot)
  Using cached networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
Collecting jinja2 (from torch<3.0.0,>=2.2.1->boxmot)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting fsspec (from torch<3.0.0,>=2.2.1->boxmot)
  Using cached fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
Collecting torch<3.0.0,>=2.2.1 (from boxmot)
  Using cached torch-2.2.2-cp311-none-macosx_11_0_arm64.whl.metadata (25 kB)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision<0.18.0,>=0.17.1->boxmot)
  Using cached pillow-10.4.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (9.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython<4.0.0,>=3.1.42->boxmot)
  Using cached smmap-5.0.1-py3-none-any.whl.metadata (4.3 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.0.0->boxmot)
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting soupsieve>1.2 (from beautifulsoup4->gdown<6.0.0,>=5.1.0->boxmot)
  Downloading soupsieve-2.6-py3-none-any.whl.metadata (4.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch<3.0.0,>=2.2.1->boxmot)
  Using cached MarkupSafe-2.1.5-cp311-cp311-macosx_10_9_universal2.whl.metadata (3.0 kB)
Collecting contourpy>=1.0.1 (from matplotlib->filterpy<2.0.0,>=1.4.5->boxmot)
  Using cached contourpy-1.3.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.4 kB)
Collecting cycler>=0.10 (from matplotlib->filterpy<2.0.0,>=1.4.5->boxmot)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->filterpy<2.0.0,>=1.4.5->boxmot)
  Downloading fonttools-4.54.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (163 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->filterpy<2.0.0,>=1.4.5->boxmot)
  Using cached kiwisolver-1.4.7-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.3 kB)
Collecting packaging>=20.0 (from matplotlib->filterpy<2.0.0,>=1.4.5->boxmot)
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting pyparsing>=2.3.1 (from matplotlib->filterpy<2.0.0,>=1.4.5->boxmot)
  Using cached pyparsing-3.1.4-py3-none-any.whl.metadata (5.1 kB)
Collecting charset-normalizer<4,>=2 (from requests[socks]->gdown<6.0.0,>=5.1.0->boxmot)
  Using cached charset_normalizer-3.3.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests[socks]->gdown<6.0.0,>=5.1.0->boxmot)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests[socks]->gdown<6.0.0,>=5.1.0->boxmot)
  Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests[socks]->gdown<6.0.0,>=5.1.0->boxmot)
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting PySocks!=1.5.7,>=1.5.6 (from requests[socks]->gdown<6.0.0,>=5.1.0->boxmot)
  Using cached PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy->torch<3.0.0,>=2.2.1->boxmot)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Downloading boxmot-10.0.84-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 7.6 MB/s eta 0:00:00
Using cached numpy-1.26.4-cp311-cp311-macosx_11_0_arm64.whl (14.0 MB)
Using cached ftfy-6.2.3-py3-none-any.whl (43 kB)
Using cached gdown-5.2.0-py3-none-any.whl (18 kB)
Using cached GitPython-3.1.43-py3-none-any.whl (207 kB)
Downloading lapx-0.5.10.post1-cp311-cp311-macosx_11_0_arm64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 7.9 MB/s eta 0:00:00
Using cached loguru-0.7.2-py3-none-any.whl (62 kB)
Using cached opencv_python-4.10.0.84-cp37-abi3-macosx_11_0_arm64.whl (54.8 MB)
Downloading pandas-2.2.3-cp311-cp311-macosx_11_0_arm64.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 9.5 MB/s eta 0:00:00
Using cached PyYAML-6.0.2-cp311-cp311-macosx_11_0_arm64.whl (172 kB)
Downloading regex-2024.9.11-cp311-cp311-macosx_11_0_arm64.whl (284 kB)
Downloading scikit_learn-1.5.2-cp311-cp311-macosx_12_0_arm64.whl (11.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 8.9 MB/s eta 0:00:00
Using cached torchvision-0.17.2-cp311-cp311-macosx_11_0_arm64.whl (1.6 MB)
Using cached torch-2.2.2-cp311-none-macosx_11_0_arm64.whl (59.7 MB)
Using cached yacs-0.1.8-py3-none-any.whl (14 kB)
Using cached gitdb-4.0.11-py3-none-any.whl (62 kB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached pillow-10.4.0-cp311-cp311-macosx_11_0_arm64.whl (3.4 MB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
Using cached scipy-1.14.1-cp311-cp311-macosx_14_0_arm64.whl (23.1 MB)
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
Using cached wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)
Using cached beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
Using cached fsspec-2024.9.0-py3-none-any.whl (179 kB)
Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Using cached matplotlib-3.9.2-cp311-cp311-macosx_11_0_arm64.whl (7.8 MB)
Using cached networkx-3.3-py3-none-any.whl (1.7 MB)
Downloading sympy-1.13.3-py3-none-any.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 6.9 MB/s eta 0:00:00
Using cached tqdm-4.66.5-py3-none-any.whl (78 kB)
Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Using cached charset_normalizer-3.3.2-cp311-cp311-macosx_11_0_arm64.whl (118 kB)
Using cached contourpy-1.3.0-cp311-cp311-macosx_11_0_arm64.whl (250 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.54.0-cp311-cp311-macosx_11_0_arm64.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 7.6 MB/s eta 0:00:00
Downloading idna-3.10-py3-none-any.whl (70 kB)
Using cached kiwisolver-1.4.7-cp311-cp311-macosx_11_0_arm64.whl (64 kB)
Using cached MarkupSafe-2.1.5-cp311-cp311-macosx_10_9_universal2.whl (18 kB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Using cached packaging-24.1-py3-none-any.whl (53 kB)
Using cached pyparsing-3.1.4-py3-none-any.whl (104 kB)
Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached smmap-5.0.1-py3-none-any.whl (24 kB)
Downloading soupsieve-2.6-py3-none-any.whl (36 kB)
Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Installing collected packages: wcwidth, pytz, mpmath, urllib3, tzdata, typing-extensions, tqdm, threadpoolctl, sympy, soupsieve, smmap, six, regex, pyyaml, PySocks, pyparsing, pillow, packaging, numpy, networkx, MarkupSafe, loguru, kiwisolver, joblib, idna, ftfy, fsspec, fonttools, filelock, cycler, charset-normalizer, certifi, yacs, scipy, requests, python-dateutil, opencv-python, lapx, jinja2, gitdb, contourpy, beautifulsoup4, torch, scikit-learn, pandas, matplotlib, gitpython, torchvision, gdown, filterpy, boxmot
Successfully installed MarkupSafe-2.1.5 PySocks-1.7.1 beautifulsoup4-4.12.3 boxmot-10.0.84 certifi-2024.8.30 charset-normalizer-3.3.2 contourpy-1.3.0 cycler-0.12.1 filelock-3.16.1 filterpy-1.4.5 fonttools-4.54.0 fsspec-2024.9.0 ftfy-6.2.3 gdown-5.2.0 gitdb-4.0.11 gitpython-3.1.43 idna-3.10 jinja2-3.1.4 joblib-1.4.2 kiwisolver-1.4.7 lapx-0.5.10.post1 loguru-0.7.2 matplotlib-3.9.2 mpmath-1.3.0 networkx-3.3 numpy-1.26.4 opencv-python-4.10.0.84 packaging-24.1 pandas-2.2.3 pillow-10.4.0 pyparsing-3.1.4 python-dateutil-2.9.0.post0 pytz-2024.2 pyyaml-6.0.2 regex-2024.9.11 requests-2.32.3 scikit-learn-1.5.2 scipy-1.14.1 six-1.16.0 smmap-5.0.1 soupsieve-2.6 sympy-1.13.3 threadpoolctl-3.5.0 torch-2.2.2 torchvision-0.17.2 tqdm-4.66.5 typing-extensions-4.12.2 tzdata-2024.2 urllib3-2.2.3 wcwidth-0.2.13 yacs-0.1.8
(myenv) ➜  yolo_boxmot git:(main) ✗ python
Python 3.11.5 (v3.11.5:cce6ba91b3, Aug 24 2023, 10:50:31) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
