### ISSUE TITLE
centroid_batch() missing 2 required positional arguments: 'w' and 'h'

### ISSUE THREAD

**Issue by JBAMeijer** [mikel-brostrom/boxmot#1671]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

There seems to be a problem when using the centroid asso_func when running the tracker.
```
tracker = OCSORT(asso_func="centroid")
```
At some point the program will run the run_asso_func in iou.py where it will crash on line 242:

<img width="1045" alt="image" src="https://github.com/user-attachments/assets/4900f76e-ef63-46f6-aa6c-6628a6dc35e0">

```
Traceback (most recent call last):
  File "/home/student/anaconda/envs/deeplearning/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/pc_deploy/bikehelmet/inference_counting_boxmot.py", line 48, in counting
    tracks = tracker.update(detections_to_track, frame)
             ^^python-BaseException
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda/envs/deeplearning/lib/python3.11/site-packages/boxmot/trackers/basetracker.py", line 135, in wrapper
    return update_method(self, dets=dets, img=img, embs=embs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda/envs/deeplearning/lib/python3.11/site-packages/boxmot/trackers/ocsort/ocsort.py", line 291, in update
    matched, unmatched_dets, unmatched_trks = associate(
                                              ^^^^^^^^^^
  File "/home/student/anaconda/envs/deeplearning/lib/python3.11/site-packages/boxmot/utils/association.py", line 146, in associate
    iou_matrix = run_asso_func(asso_func, detections, trackers, w, h)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda/envs/deeplearning/lib/python3.11/site-packages/boxmot/utils/iou.py", line 242, in run_asso_func
    return func(*args[0:2])
           ^^^^^^^^^^^^^^^^
TypeError: centroid_batch() missing 2 required positional arguments: 'w' and 'h'
```
When I checked for recent commits there was a change 2 weeks ago that added the "centroid_batch" to the first and second if statement.
https://github.com/mikel-brostrom/boxmot/commit/3af9031f3550d7944687d5fa8cc7847c072df38c

Removing the "Centroid_batch" from that second if statement makes it evaluate the elif which seems to fix the problem.

I don't know if this change was done intentionally. If not, do you want me to make a pull request to fix it?

### Environment

Boxmot 11.0.0, python 3.11.9,  cuda12.4

### Minimal Reproducible Example

run with
```
tracker = OCSORT(asso_func="centroid")
```
then call 
```
tracks = tracker.update(detections_to_track, frame)
```

**Comment by YouriStudent** [comment]
I have the same problem

**Comment by mikel-brostrom** [comment]
I see. Looking into this right now 🚀
