### ISSUE TITLE
AttributeError: 'ByteTrack' object has no attribute 'reset' occurred after executing the track.exe file

### ISSUE THREAD

**Issue by starlook** [mikel-brostrom/boxmot#1695]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

D:\Anaconda\envs\boxmot\python.exe "D:/Code soft/Code/Pycharm project/boxmot-master/tracking/track.py"

Traceback (most recent call last):
  File "D:\Code soft\Code\Pycharm project\boxmot-master\tracking\track.py", line 174, in <module>
    run(opt)
  File "D:\Anaconda\envs\boxmot\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\Code soft\Code\Pycharm project\boxmot-master\tracking\track.py", line 103, in run
    for r in results:
  File "D:\Anaconda\envs\boxmot\lib\site-packages\torch\utils\_contextlib.py", line 36, in generator_context
    response = gen.send(None)
  File "D:\Anaconda\envs\boxmot\lib\site-packages\ultralytics\engine\predictor.py", line 262, in stream_inference
    self.run_callbacks("on_predict_postprocess_end")
  File "D:\Anaconda\envs\boxmot\lib\site-packages\ultralytics\engine\predictor.py", line 399, in run_callbacks
    callback(self)
  File "D:\Anaconda\envs\boxmot\lib\site-packages\ultralytics\trackers\track.py", line 74, in on_predict_postprocess_end
    tracker.reset()
AttributeError: 'ByteTrack' object has no attribute 'reset'

Process finished with exit code 1

### Environment

(boxmot) D:\Code soft\Code\Pycharm project\boxmot-master>conda list
# packages in environment at D:\Anaconda\envs\boxmot:
#
# Name                    Version                   Build  Channel
absl-py                   2.1.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
aiohappyeyeballs          2.4.3                    pypi_0    pypi
aiohttp                   3.10.9                   pypi_0    pypi
aiohttp-retry             2.8.3                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
albucore                  0.0.17                   pypi_0    pypi
albumentations            1.3.1                    pypi_0    pypi
aliyun-python-sdk-core    2.15.2                   pypi_0    pypi
aliyun-python-sdk-kms     2.16.5                   pypi_0    pypi
amqp                      5.2.0                    pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
asyncssh                  2.17.0                   pypi_0    pypi
atpublic                  5.0                      pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
automat                   24.8.1                   pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
billiard                  4.2.1                    pypi_0    pypi
ca-certificates           2024.8.30            h56e8100_0    conda-forge
cachetools                5.5.0                    pypi_0    pypi
cattrs                    24.1.2                   pypi_0    pypi
celery                    5.4.0                    pypi_0    pypi
certifi                   2022.12.7                pypi_0    pypi
cffi                      1.17.1                   pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
chex                      0.1.87                   pypi_0    pypi
clearml                   1.16.4                   pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
click-didyoumean          0.3.1                    pypi_0    pypi
click-plugins             1.1.1                    pypi_0    pypi
click-repl                0.3.0                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
comet                     3.1.0                    pypi_0    pypi
configobj                 5.0.9                    pypi_0    pypi
constantly                23.10.4                  pypi_0    pypi
contourpy                 1.3.0                    pypi_0    pypi
coremltools               8.0                      pypi_0    pypi
crcmod                    1.7                      pypi_0    pypi
cryptography              43.0.1                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
deep-sort-realtime        1.3.2                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
dictdiffer                0.9.0                    pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
diskcache                 5.6.3                    pypi_0    pypi
distro                    1.9.0                    pypi_0    pypi
dpath                     2.2.0                    pypi_0    pypi
dulwich                   0.22.1                   pypi_0    pypi
dvc                       3.55.2                   pypi_0    pypi
dvc-data                  3.16.6                   pypi_0    pypi
dvc-http                  2.32.0                   pypi_0    pypi
dvc-objects               5.1.0                    pypi_0    pypi
dvc-render                1.0.2                    pypi_0    pypi
dvc-studio-client         0.21.0                   pypi_0    pypi
dvc-task                  0.40.1                   pypi_0    pypi
dvclive                   3.48.0                   pypi_0    pypi
efficientnet-pytorch      0.7.1                    pypi_0    pypi
einops                    0.8.0                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
etils                     1.5.2                    pypi_0    pypi
eval-type-backport        0.2.0                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
executing                 2.1.0                    pypi_0    pypi
ffmpeg                    1.4                      pypi_0    pypi
filelock                  3.14.0                   pypi_0    pypi
filetype                  1.2.0                    pypi_0    pypi
filterpy                  1.4.5                    pypi_0    pypi
flatbuffers               24.3.25                  pypi_0    pypi
flatten-dict              0.4.2                    pypi_0    pypi
flax                      0.8.5                    pypi_0    pypi
flufl-lock                8.1.0                    pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.9.0                 pypi_0    pypi
ftfy                      6.3.0                    pypi_0    pypi
funcy                     2.0                      pypi_0    pypi
furl                      2.1.3                    pypi_0    pypi
gast                      0.6.0                    pypi_0    pypi
gdown                     5.2.0                    pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.43                   pypi_0    pypi
google-auth               2.35.0                   pypi_0    pypi
google-auth-oauthlib      1.2.1                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grad-cam                  1.4.8                    pypi_0    pypi
grandalf                  0.8                      pypi_0    pypi
grpcio                    1.66.2                   pypi_0    pypi
gto                       1.7.1                    pypi_0    pypi
h5py                      3.12.1                   pypi_0    pypi
huggingface-hub           0.25.1                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
humanize                  4.11.0                   pypi_0    pypi
hydra-core                1.3.2                    pypi_0    pypi
hyperlink                 21.0.0                   pypi_0    pypi
idna                      3.7                      pypi_0    pypi
imageio                   2.35.1                   pypi_0    pypi
importlib-metadata        8.5.0                    pypi_0    pypi
importlib-resources       6.4.5                    pypi_0    pypi
incremental               24.7.2                   pypi_0    pypi
intel-openmp              2024.2.1          h57928b3_1083    conda-forge
ipython                   8.18.1                   pypi_0    pypi
iterative-telemetry       0.0.9                    pypi_0    pypi
jax                       0.4.30                   pypi_0    pypi
jaxlib                    0.4.30                   pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
keras                     2.15.0                   pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
kombu                     5.4.2                    pypi_0    pypi
lap                       0.4.0           py39h2e25243_1005    conda-forge
lazy-loader               0.4                      pypi_0    pypi
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libclang                  18.1.1                   pypi_0    pypi
liblapack                 3.9.0                     8_mkl    conda-forge
loguru                    0.7.2                    pypi_0    pypi
lxml                      5.3.0                    pypi_0    pypi
markdown                  3.7                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.2                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2020.4             hb70f87d_311    conda-forge
ml-dtypes                 0.3.2                    pypi_0    pypi
mmcv                      2.0.1                    pypi_0    pypi
mmengine                  0.10.5                   pypi_0    pypi
model-index               0.1.11                   pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
msgpack                   1.1.0                    pypi_0    pypi
multidict                 6.1.0                    pypi_0    pypi
namex                     0.0.8                    pypi_0    pypi
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  3.1                      pypi_0    pypi
numpy                     1.26.3                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
onnx                      1.14.0                   pypi_0    pypi
onnxruntime               1.15.1                   pypi_0    pypi
onnxsim                   0.4.36                   pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
opencv-python-headless    4.10.0.84                pypi_0    pypi
opendatalab               0.0.10                   pypi_0    pypi
openmim                   0.3.9                    pypi_0    pypi
openssl                   3.0.15               h827c3e9_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
openvino                  2024.4.0                 pypi_0    pypi
openvino-dev              2024.4.0                 pypi_0    pypi
openvino-telemetry        2024.1.0                 pypi_0    pypi
openxlab                  0.1.1                    pypi_0    pypi
opt-einsum                3.4.0                    pypi_0    pypi
optax                     0.2.3                    pypi_0    pypi
optree                    0.13.0                   pypi_0    pypi
orbax-checkpoint          0.6.4                    pypi_0    pypi
ordered-set               4.1.0                    pypi_0    pypi
orderedmultidict          1.0.1                    pypi_0    pypi
orjson                    3.10.7                   pypi_0    pypi
oss2                      2.17.0                   pypi_0    pypi
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
pathlib2                  2.3.7.post1              pypi_0    pypi
pathspec                  0.12.1                   pypi_0    pypi
pillow                    10.2.0                   pypi_0    pypi
pip                       24.2             py39haa95532_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
platformdirs              3.11.0                   pypi_0    pypi
prompt-toolkit            3.0.48                   pypi_0    pypi
protobuf                  3.20.3                   pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
pure-eval                 0.2.3                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyaml                     24.9.0                   pypi_0    pypi
pyasn1                    0.6.1                    pypi_0    pypi
pyasn1-modules            0.4.1                    pypi_0    pypi
pybind11                  2.13.6                   pypi_0    pypi
pycocotools               2.0.8                    pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pycryptodome              3.21.0                   pypi_0    pypi
pydantic                  2.9.2                    pypi_0    pypi
pydantic-core             2.23.4                   pypi_0    pypi
pydot                     3.0.2                    pypi_0    pypi
pygit2                    1.15.1                   pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pygtrie                   2.5.0                    pypi_0    pypi
pyjwt                     2.8.0                    pypi_0    pypi
pynvml                    11.5.3                   pypi_0    pypi
pyparsing                 3.1.4                    pypi_0    pypi
pyreadline3               3.5.3                    pypi_0    pypi
pysocks                   1.7.1                    pypi_0    pypi
python                    3.9.19               h1aa4202_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.9.0.post0              pypi_0    pypi
python-dotenv             1.0.1                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytorch-wavelets          1.3.0                    pypi_0    pypi
pytz                      2023.4                   pypi_0    pypi
pywavelets                1.6.0                    pypi_0    pypi
pywin32                   307                      pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
qudida                    0.0.4                    pypi_0    pypi
referencing               0.35.1                   pypi_0    pypi
regex                     2024.9.11                pypi_0    pypi
requests                  2.28.2                   pypi_0    pypi
requests-oauthlib         2.0.0                    pypi_0    pypi
requests-toolbelt         1.0.0                    pypi_0    pypi
rich                      13.4.2                   pypi_0    pypi
roboflow                  1.1.47                   pypi_0    pypi
rpds-py                   0.20.0                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
ruamel-yaml               0.18.6                   pypi_0    pypi
ruamel-yaml-clib          0.2.8                    pypi_0    pypi
safetensors               0.4.5                    pypi_0    pypi
scikit-image              0.24.0                   pypi_0    pypi
scikit-learn              1.5.2                    pypi_0    pypi
scipy                     1.13.1                   pypi_0    pypi
scmrepo                   3.3.8                    pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
semver                    3.0.2                    pypi_0    pypi
setuptools                60.2.0                   pypi_0    pypi
shellingham               1.5.4                    pypi_0    pypi
shortuuid                 1.0.13                   pypi_0    pypi
shtab                     1.7.1                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.1                    pypi_0    pypi
sounddevice               0.5.0                    pypi_0    pypi
soupsieve                 2.6                      pypi_0    pypi
sqlite                    3.45.3               h2bbff1b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
sqltrie                   0.11.1                   pypi_0    pypi
stack-data                0.6.3                    pypi_0    pypi
sympy                     1.13.3                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tensorboard               2.15.2                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tensorflow                2.15.1                   pypi_0    pypi
tensorflow-decision-forests 1.8.1                    pypi_0    pypi
tensorflow-estimator      2.15.0                   pypi_0    pypi
tensorflow-hub            0.16.1                   pypi_0    pypi
tensorflow-intel          2.15.1                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.31.0                   pypi_0    pypi
tensorflowjs              4.21.0                   pypi_0    pypi
tensorstore               0.1.66                   pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
tf-keras                  2.15.1                   pypi_0    pypi
tflite-support            0.4.3                    pypi_0    pypi
thop                      0.1.1-2209072238          pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tidecv                    1.0.1                    pypi_0    pypi
tifffile                  2024.8.30                pypi_0    pypi
timm                      0.9.8                    pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
tomlkit                   0.13.2                   pypi_0    pypi
toolz                     1.0.0                    pypi_0    pypi
torch                     2.4.1                    pypi_0    pypi
torchaudio                2.4.1                    pypi_0    pypi
torchvision               0.19.1                   pypi_0    pypi
tqdm                      4.65.2                   pypi_0    pypi
traitlets                 5.14.3                   pypi_0    pypi
ttach                     0.0.3                    pypi_0    pypi
twisted                   24.7.0                   pypi_0    pypi
typer                     0.12.5                   pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
ultralytics               8.3.6                    pypi_0    pypi
ultralytics-thop          2.0.6                    pypi_0    pypi
urllib3                   1.26.13                  pypi_0    pypi
vc                        14.40                h2eaa2aa_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
vine                      5.1.0                    pypi_0    pypi
voluptuous                0.15.2                   pypi_0    pypi
vs2015_runtime            14.40.33807          h98bb1dd_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
wcwidth                   0.2.13                   pypi_0    pypi
werkzeug                  3.0.4                    pypi_0    pypi
wheel                     0.44.0           py39haa95532_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
win32-setctime            1.1.0                    pypi_0    pypi
wrapt                     1.14.1                   pypi_0    pypi
wurlitzer                 3.1.1                    pypi_0    pypi
yapf                      0.40.2                   pypi_0    pypi
yarl                      1.13.1                   pypi_0    pypi
zc-lockfile               3.0.post1                pypi_0    pypi
zipp                      3.20.2                   pypi_0    pypi
zope-interface            7.0.3                    pypi_0    pypi

### Minimal Reproducible Example

# Mikel Broström 🔥 Yolo Tracking 🧾 AGPL-3.0 license

import argparse
import cv2
import numpy as np
from functools import partial
from pathlib import Path

import torch

from boxmot import TRACKERS
from boxmot.tracker_zoo import create_tracker
from boxmot.utils import ROOT, WEIGHTS, TRACKER_CONFIGS
from boxmot.utils.checks import RequirementsChecker
from tracking.detectors import get_yolo_inferer

checker = RequirementsChecker()
checker.check_packages(('ultralytics @ git+https://github.com/mikel-brostrom/ultralytics.git', ))  # install

from ultralytics import YOLO
from ultralytics.utils.plotting import Annotator, colors
from ultralytics.data.utils import VID_FORMATS
from ultralytics.utils.plotting import save_one_box

def on_predict_start(predictor, persist=False):
    """
    Initialize trackers for object tracking during prediction.

    Args:
        predictor (object): The predictor object to initialize trackers for.
        persist (bool, optional): Whether to persist the trackers if they already exist. Defaults to False.
    """

    assert predictor.custom_args.tracking_method in TRACKERS, \
        f"'{predictor.custom_args.tracking_method}' is not supported. Supported ones are {TRACKERS}"

    tracking_config = TRACKER_CONFIGS / (predictor.custom_args.tracking_method + '.yaml')
    trackers = []
    for i in range(predictor.dataset.bs):
        tracker = create_tracker(
            predictor.custom_args.tracking_method,
            tracking_config,
            predictor.custom_args.reid_model,
            predictor.device,
            predictor.custom_args.half,
            predictor.custom_args.per_class
        )
        # motion only modeles do not have
        if hasattr(tracker, 'model'):
            tracker.model.warmup()
        trackers.append(tracker)

    predictor.trackers = trackers

@torch.no_grad()
def run(args):
    
    ul_models = ['yolov8', 'yolov9', 'yolov10', 'rtdetr', 'sam']

    yolo = YOLO(
        args.yolo_model if any(yolo in str(args.yolo_model) for yolo in ul_models) else 'yolov8n.pt',
    )

    results = yolo.track(
        source=args.source,
        conf=args.conf,
        iou=args.iou,
        agnostic_nms=args.agnostic_nms,
        show=False,
        stream=True,
        device=args.device,
        show_conf=args.show_conf,
        save_txt=args.save_txt,
        show_labels=args.show_labels,
        save=True,
        verbose=args.verbose,
        exist_ok=args.exist_ok,
        project=args.project,
        name=args.name,
        classes=args.classes,
        imgsz=args.imgsz,
        vid_stride=args.vid_stride,
        line_width=args.line_width
    )

    yolo.add_callback('on_predict_start', partial(on_predict_start, persist=True))

    if not any(yolo in str(args.yolo_model) for yolo in ul_models):
        # replace yolov8 model
        m = get_yolo_inferer(args.yolo_model)
        model = m(
            model=args.yolo_model,
            device=yolo.predictor.device,
            args=yolo.predictor.args
        )
        yolo.predictor.model = model

    # store custom args in predictor
    yolo.predictor.custom_args = args

    for r in results:

        img = yolo.predictor.trackers[0].plot_results(r.orig_img, args.show_trajectories)

        if args.show is True:
            cv2.imshow('BoxMOT', img)     
            key = cv2.waitKey(1) & 0xFF
            if key == ord(' ') or key == ord('q'):
                break

def parse_opt():
    parser = argparse.ArgumentParser()
    parser.add_argument('--yolo-model', type=Path, default=WEIGHTS / 'weights/yolov8n.pt',
                        help='yolo model path')
    parser.add_argument('--reid-model', type=Path, default=WEIGHTS / 'weights/osnet_x0_25_msmt17.pt',
                        help='reid model path')
    parser.add_argument('--tracking-method', type=str, default='bytetrack',
                        help='deepocsort, botsort, strongsort, ocsort, bytetrack, imprassoc')
    parser.add_argument('--source', type=str, default='F:\data\行人检测测试视频.mp4',
                        help='file/dir/URL/glob, 0 for webcam')
    parser.add_argument('--imgsz', '--img', '--img-size', nargs='+', type=int, default=[640],
                        help='inference size h,w')
    parser.add_argument('--conf', type=float, default=0.5,
                        help='confidence threshold')
    parser.add_argument('--iou', type=float, default=0.7,
                        help='intersection over union (IoU) threshold for NMS')
    parser.add_argument('--device', default='',
                        help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
    parser.add_argument('--show', action='store_true',
                        help='display tracking video results')
    parser.add_argument('--save', action='store_true',
                        help='save video tracking results')
    # class 0 is person, 1 is bycicle, 2 is car... 79 is oven
    parser.add_argument('--classes', nargs='+', type=int,
                        help='filter by class: --classes 0, or --classes 0 2 3')
    parser.add_argument('--project', default=ROOT / 'runs' / 'track',
                        help='save results to project/name')
    parser.add_argument('--name', default='exp',
                        help='save results to project/name')
    parser.add_argument('--exist-ok', action='store_true',
                        help='existing project/name ok, do not increment')
    parser.add_argument('--half', action='store_true',
                        help='use FP16 half-precision inference')
    parser.add_argument('--vid-stride', type=int, default=1,
                        help='video frame-rate stride')
    parser.add_argument('--show-labels', action='store_false',
                        help='either show all or only bboxes')
    parser.add_argument('--show-conf', action='store_false',
                        help='hide confidences when show')
    parser.add_argument('--show-trajectories', action='store_true',
                        help='show confidences')
    parser.add_argument('--save-txt', action='store_true',
                        help='save tracking results in a txt file')
    parser.add_argument('--save-id-crops', action='store_true',
                        help='save each crop to its respective id folder')
    parser.add_argument('--line-width', default=None, type=int,
                        help='The line width of the bounding boxes. If None, it is scaled to the image size.')
    parser.add_argument('--per-class', default=False, action='store_true',
                        help='not mix up classes when tracking')
    parser.add_argument('--verbose', default=True, action='store_true',
                        help='print results per frame')
    parser.add_argument('--agnostic-nms', default=False, action='store_true',
                        help='class-agnostic NMS')

    opt = parser.parse_args()
    return opt

if __name__ == "__main__":
    opt = parse_opt()
    run(opt)

**Comment by starlook** [comment]
Choosing other trackers, such as Deepocport, is also the same mistake
