### ISSUE TITLE
AttributeError: 'DeepOcSort' object has no attribute 'reset'

### ISSUE THREAD

**Issue by Keqi19** [mikel-brostrom/boxmot#1772]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

AttributeError: 'DeepOcSort' object has no attribute 'reset'

**Comment by max-unfinity** [comment]
The same.
Run with args:
```
"args": [
                "--yolo-model",
                "yolov10n",
                "--reid-model",
                "osnet_x1_0_msmt17.pt",
                "--tracking-method",
                "bytetrack",
                "--source",
                "../data/bdd100k/images/track/val/b1c9c847-3bda4659",
                "--device",
                "cuda",
                "--save",
            ]
```

Traceback:
```
  File "tracking/track.py", line 186, in <module>
    run(opt)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "tracking/track.py", line 114, in run
    for r in results:
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/predictor.py", line 262, in stream_inference
    self.run_callbacks("on_predict_postprocess_end")
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/predictor.py", line 399, in run_callbacks
    callback(self)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/trackers/track.py", line 74, in on_predict_postprocess_end
    tracker.reset()
AttributeError: 'ByteTrack' object has no attribute 'reset'
```

Version:
- ultralytics==8.3.18 (the latest version doesn't work too)

**Comment by max-unfinity** [comment]
BoxMOT requires custom ultralytics package. So we need to install it:

```
pip uninstall ultralytics -y
pip install --upgrade pip setuptools wheel
pip install git+https://github.com/mikel-brostrom/ultralytics.git
```

**Comment by type055-renhai** [comment]
我也遇到了这个bug，我重新创了个虚拟环境，把python解释器从3.9换到3.12就没问题了，应该是至少要3.10版本的才行

**Comment by Keqi19** [comment]
> 我也遇到了这个bug，我重新创了个虚拟环境，把python解释器从3.9换到3.12就没问题了，应该是至少要3.10版本的才行

换成3.12之后，报这个错：
Traceback (most recent call last):
  File "F:\lab-2\models\boxmot-master\tracking\track.py", line 186, in <module>
    run(opt)
  File "D:\Anaconda3\envs\boxmot-py3.12\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\lab-2\models\boxmot-master\tracking\track.py", line 114, in run
    for r in results:
             ^^^^^^^
  File "D:\Anaconda3\envs\boxmot-py3.12\Lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "D:\Anaconda3\envs\boxmot-py3.12\Lib\site-packages\ultralytics\engine\predictor.py", line 267, in stream_inference
    self.run_callbacks("on_predict_postprocess_end")
  File "D:\Anaconda3\envs\boxmot-py3.12\Lib\site-packages\ultralytics\engine\predictor.py", line 404, in run_callbacks
    callback(self)
  File "D:\Anaconda3\envs\boxmot-py3.12\Lib\site-packages\ultralytics\trackers\track.py", line 74, in on_predict_postprocess_end
    tracker.reset()
    ^^^^^^^^^^^^^
AttributeError: 'DeepOcSort' object has no attribute 'reset'

Process finished with exit code 1

**Comment by Keqi19** [comment]
> pip install git+https://github.com/mikel-brostrom/ultralytics.git
What version of ultralytics is it?

**Comment by mikel-brostrom** [comment]
You are still not following the installation instructions... Closing. `boxmot` uses a custom `ultralytics` version for tracking which you are not installing. As already explained by @max-unfinity

**Comment by m7mdhka** [comment]
@mikel-brostrom is the custom ultralytics is continuosly updated?

**Comment by mikel-brostrom** [comment]
Boxmot now uses the official ultralytics package 😊

**Comment by mikel-brostrom** [comment]
And yes. It is updated continuously

**Comment by m7mdhka** [comment]
@mikel-brostrom thanks sir 
so the `self.model.add_callback('on_predict_start', initialize_boxmot_trackers)` will works with new boxmot?

**Comment by m7mdhka** [comment]
@mikel-brostrom 1 more question
how can i move the tracker  and the model to a thread?
for yolo just i need to initilize it inside thread, what about th tracker? is there any thing i need to concern about?
