### ISSUE TITLE
AttributeError: 'DeepOcSort' object has no attribute 'reset'. 

### ISSUE THREAD

**Issue by Keqi19** [mikel-brostrom/boxmot#1780]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

2024-12-21 20:37:36.326 | INFO     | boxmot.utils.torch_utils:select_device:52 - Yolo Tracking v11.0.6 🚀 Python-3.9.21 torch-2.2.2
CUDA:0 (NVIDIA GeForce RTX 4060 Ti, 16380MiB)
2024-12-21 20:37:36.372 | SUCCESS  | boxmot.appearance.reid_model_factory:load_pretrained_weights:183 - Loaded pretrained weights from pretrained\osnet_x0_25_msmt17.pt
Traceback (most recent call last):
  File "F:\lab-2\models\boxmot-master\tracking\track.py", line 186, in <module>
    run(opt)
  File "D:\Anaconda3\envs\boxmot\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\lab-2\models\boxmot-master\tracking\track.py", line 114, in run
    for r in results:
  File "D:\Anaconda3\envs\boxmot\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "D:\Anaconda3\envs\boxmot\lib\site-packages\ultralytics\engine\predictor.py", line 267, in stream_inference
    self.run_callbacks("on_predict_postprocess_end")
  File "D:\Anaconda3\envs\boxmot\lib\site-packages\ultralytics\engine\predictor.py", line 404, in run_callbacks
    callback(self)
  File "D:\Anaconda3\envs\boxmot\lib\site-packages\ultralytics\trackers\track.py", line 74, in on_predict_postprocess_end
    tracker.reset()
AttributeError: 'DeepOcSort' object has no attribute 'reset'

**Comment by yl342643820** [comment]
I also had the same problem. I followed and found that there was no reset () function in the tracker class.

**Comment by meiqiu-CUMT** [comment]
I found that there's only update() in the tracker class. So I make the reset() to the update(). Then another question just jump on my face. And i'm crying with no tears.....

**Comment by lly456** [comment]
same problem~

**Comment by Keqi19** [comment]
> same problem~

You can refer to this link: https://github.com/JackWoo0831/Yolov7-tracker/tree/v2.

**Comment by Keqi19** [comment]
> I found that there's only update() in the tracker class. So I make the reset() to the update(). Then another question just jump on my face. And i'm crying with no tears.....

You can refer to this link: https://github.com/JackWoo0831/Yolov7-tracker/tree/v2.

**Comment by BboyHanat** [comment]
add   
`  def reset(self):
        self.active_tracks = []`
to BaseTracker class, can solve this issue

**Comment by rongyixiao180319** [comment]
reason: ultralytics is Incorrect version. ultralytics is v8.0.146.
git clone https://github.com/mikel-brostrom/ultralytics.git .Put ultralytics in a directory.copy ultralytics/ultralytics to boxmot. This solves the problem。
